### ISSUE TITLE
method: "GET" needs to be "get" to work

### ISSUE THREAD

**Issue by shawn98ag** [ringier-data/snowplow-reactjs-native-tracker#3]
https://github.com/ringier-data/snowplow-reactjs-native-tracker/blob/6265238c85ea88c4e6b7daef75569274feaaca25/src/lib/Emitter.js#L41

I'd recommend adding `.toLowerCase()` to this check on `method`. Your documentation suggests using "GET" but I had to use "get" for it to work in my setup.

**Comment by benjackwhite** [comment]
Good catch and suggestion 👍

**Comment by benjackwhite** [comment]
We have decided to deprecate this library in favour of the full https://github.com/ringier-data/ringier-pixel-javascript-web. This issue is fixed there as this part of the implementation is no longer available
